name: Glue ETL Pipeline

on:
  push:
    branches: [main]

jobs:
  etl-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Trigger Glue ETL Job
      run: |
        aws glue start-job-run \
          --job-name firstjob \
          --arguments '{
            "--JOB_NAME": "firstjob",
            "--SOURCE_PATH": "s3://opbkt-glue/processed-output/",
            "--TARGET_PATH": "s3://gpbkt/cleaned/"
          }'

    - name: Wait for Glue Job to finish
      run: |
        echo "Waiting for Glue job to finish..."
        # Optional: implement polling logic if needed

    - name: Trigger Glue Crawler
      run: |
        aws glue start-crawler --name nyc-crawler
