name: Upload Glue Script to S3

on:
  push:
    branches: [Gyandeep]  # or the branch you're using

jobs:
  upload-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Upload Glue Script to S3
        run: |
          aws s3 cp etl/etl-glue-script.py s3://first-glue-bkt-grp-three-nyc/scripts/etl-glue-script.py
          echo "✅ Glue script uploaded to S3."
      
      - name: Upload Parquet Data to S3
        run: |
          aws s3 cp data/part-00000-138827fc-5f4e-468e-aa87-5a4b0adc8fc0-c000.snappy.parquet s3://first-glue-bkt-grp-three-nyc/raw_data/
          echo "✅ Parquet data file uploaded to S3."
