name: Deploy Glue ETL Pipeline

on:
  push:
    branches: [pranav_CI/CD]
#hhhhgiygi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Plan
      run: terraform plan
      working-directory: terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform

    - name: Start Glue Job
      run: |
        aws glue start-job-run \
          --job-name firstjob \
          --arguments '{
            "--JOB_NAME": "firstjob",
            "--SOURCE_PATH": "s3://opbkt-glue/processed-output/",
            "--TARGET_PATH": "s3://gpbkttt/cleaned/"
          }'

    - name: Start Glue Crawler
      run: |
        aws glue start-crawler --name nyc-crawler
